### ISSUE TITLE
Make semicolons optional

### ISSUE THREAD

**Issue by curvedmark** [curvedmark/roole#103]

**Comment by curvedmark** [comment]
This prevents lists to be broken into different lines. Not a good idea:

``` css
body {
    margin: 0
    padding: 0
}
```
