### ISSUE TITLE
Support mixin selectors

### ISSUE THREAD

**Issue by curvedmark** [curvedmark/roole#109]
``` css
.btn {
    display: inline-block;
}

#submit {
    @mixin .btn;
}
```

compiles to 

``` css
.btn {
    display: inline-block;
}

#submit {
    display: inline-block;
}
```

**Comment by curvedmark** [comment]
Landed in master.

This feature is currently experimental, because it introduces a slightly strange syntax.

``` css
@media screen {
    .btn {
        display: inline-block;
    }
}

.submit {
    @mixin .btn / screen;
}
```

compiles to

``` css
@media screen {
    .btn {
        display: inline-block;
    }
}

.submit {
    display: inline-block;
}
```

It's possible to mixin rulesets nested in a media. So a media query is specified after the selector. If no media query is specified, it only mixins top-level rulesets.

Not sure if people find this feature intuitive or will ever use it. If it turns out that it brings more confusion than benefits, this feature will be dropped. Let's see how it goes.
