### ISSUE TITLE
TypeError: Arguments to path.resolve must be strings

### ISSUE THREAD

**Issue by mishanga** [curvedmark/roole#115]
CLI:

``` css
/* test.roo */
div { background: url(../../../logo.png) }
```

``` bash
./node_modules/.bin/roole test.roo
```

Result — OK:

``` css
/* test.css */
div {
    background: url(../../../logo.png);
}
```

---

Require:

``` javascript
require('roole').compile(
    'div { background: url(../../../logo.png) }',
    {},
    function(err, res){
        console.log(err || res);
    }
);
```

Result — Error:

``` bash
./node_modules/.bin/roole test.js
[TypeError: Arguments to path.resolve must be strings]
```

Hack: `compile('...', { out: './' }, function(...){...}`

Debug info:

``` bash
node -v
v0.10.9
 ./node_modules/.bin/roole -v
0.5.1
```
