### ISSUE TITLE
Variables are used after being redefined

### ISSUE THREAD

**Issue by mishanga** [curvedmark/roole#116]
Source:

```
$input = @function { .input { border: 0; } };
$button = @function { .button { padding: 0; } };

$__base = $input;
$input = @function { @mixin $__base(); .input { color: red; } };

$__base = $button;
$button = @function { @mixin $__base(); .button { color: blue; } };

.page { @mixin $input(); @mixin $button(); }
```

Result:

``` css
.page .button { padding: 0; }
.page .input { color: red; }
.page .button { padding: 0; }
.page .button { color: blue; }
```

Expected:

``` css
.page .input { border: 0; }
.page .input { color: red; }
.page .button { padding: 0; }
.page .button { color: blue; }
```

**Comment by mishanga** [comment]
What is the right way to extend or override a function?

**Comment by curvedmark** [comment]
The result is correct. Since you ask `$input` to use `$__base`, by the time `$input` is called, `$__base` is `$button`.

Try this:

``` css
$input = @function { .input { border: 0; } };
$button = @function { .button { padding: 0; } };

$__input = $input;
$input = @function { @mixin $__input(); .input { color: red; } };

$__button = $button;
$button = @function { @mixin $__button(); .button { color: blue; } };

.page { @mixin $input(); @mixin $button(); }
```

**Comment by mishanga** [comment]
OK, I got it. It was just unexpectable — not like in JavaScript.

What if I need to extend function more than 2 times?

**Comment by curvedmark** [comment]
> OK, I got it. It was just unexpectable — not like in JavaScript.

javascript also behaves like this.

``` javascript
input = function () { return 1 };
button = function () { return 2 };

__base = input;
input = function () { return __base() };

__base = button;
button = function () { return __base() };

console.log(input(), button());
```

> What if I need to extend function more than 2 times?

Keep using different temp names. What are you trying to do really? Tasks like these should be done with `@extend`.

**Comment by mishanga** [comment]
Here is almost real example.

File structure:

```
common.blocks/input/input.roo
touch.blocks/input/input.roo
touch-phone.blocks/input/input.roo
touch-phone.pages/index/index.roo
```

common.blocks/input/input.roo

``` css
$input = @function { .input { border: 0 } };
```

touch.blocks/input/input.roo

``` css
$__base = $input;
$input = @function { @mixin $__base(); .input { color: red } };
```

touch-phone.blocks/input/input.roo

``` css
$__base = $input;
$input = @function { @mixin $__base(); .input { user-select: none } };
```

touch-phone.pages/index/index.roo

``` css
@import '../../common.blocks/input/input.roo';
@import '../../touch.blocks/input/input.roo';
@import '../../touch-phone.blocks/input/input.roo';
```

touch-phone.pages/index/index.css

``` css
.input { border: 0 }
.input { color: red }
.input { user-select: none }
```

After CSSO:
touch-phone.pages/index/_index.css

``` css
.input{border:0;color:red;user-select:none}
```

**Comment by curvedmark** [comment]
Why doesn't this work?

common.blocks/input/input.roo

``` css
.input { border: 0 }
```

touch.blocks/input/input.roo

``` css
.input { color: red }
```

touch-phone.blocks/input/input.roo

``` css
.input { user-select: none }
```

touch-phone.pages/index/index.roo

``` css
@import '../../common.blocks/input/input.roo';
@import '../../touch.blocks/input/input.roo';
@import '../../touch-phone.blocks/input/input.roo';
```
