### ISSUE TITLE
Roole Javascript API error on compilation

### ISSUE THREAD

**Issue by chrisenytc** [curvedmark/roole#127]
When compiling this code css using the Roole Javascript API in node.js this error occurs. This is a new bug or a problem that can be solved fast?

``` css
.logo {
background: url('img/livia.png');
}
```

Error: `[Error: Missing base option]`

What the problem?
