### ISSUE TITLE
Don't treat two slashes in background url as comment

### ISSUE THREAD

**Issue by tadatuta** [curvedmark/roole#133]
Test case:

``` css
body {
    background: url(//example.com/image.png)
}
```

Expected to be treated as valid background url.
