### ISSUE TITLE
Add to Media Queries 

### ISSUE THREAD

**Issue by jamiebuilds** [curvedmark/roole#49]
I've had a problem that cannot currently be solved by any preprocessor. I want to have a single media query for a certain screen size and be able to add from it inline.

``` sass
@media (min-width: 960px)
@media (min-width: 1200px)

.foo
    @media (min-width: 960px)
        width: 400px
        background: red
    @media (min-width: 1200px)
        border: 3px solid green
.bar
    @media (min-width: 1200px)
        color: yellow
```

``` css
@media (min-width: 960) {
    .foo { 
        width: 400px;
        background: red;
    }
}
@media (min-width: 1200px) {
    .foo {
        border: 3px solid green;
    }
    .bar {
        color: yellow;
    }
}
```

Being able to do this would help create more organized code without making the compiled version too hefty.
