### ISSUE TITLE
Access range at index

### ISSUE THREAD

**Issue by chrisui** [curvedmark/roole#89]
It would be great if we could get the value from a range at the given index. This would open up a lot of possibilities for creating 'style maps'.

Eg.

``` css
$styles = white, black, red;
$styleBackgrounds = #fff, #000, #ff000;
$styleBorderWidths = 1px, 3px, 5px;

@for $style, $i in $styles {
  .style-block-$style {
    background: styleBackgrounds[$i],
    border: $styleBorderWidths[$i] solid black;
  }
}
```

Here we are basically defining a list of styles and using the index to get values out of multiple ranges. We could get the same functionality out of having some kind of 'roole object' syntax but I feel being able to get a value out of a range at index is some low level functionality it would be nice to provide.
