### ISSUE TITLE
Make relative urls dynamic

### ISSUE THREAD

**Issue by mdevils** [curvedmark/roole#99]
I want to define functions from JS code and use them in roole.

In my case I need to change behavior of `url()` function to make relative path (based on file, where `url()` was called).

For instance:

**tmp/base.rl:**

``` css
@import 'block/include.rl';
```

**tmp/block/include.rl:**

``` css
.block {
    background: url('1.png');
}
```

And when I run:

```
./node_modules/.bin/roole tmp/base.rl tmp
```

I want to have:

**tmp/base.rl.css:**

``` css
.block {
    background: url('block/1.png');
}
```

I'm ready to implement function myself, I only need the way to redeclare `url` function.

**Comment by makishvili** [comment]
+1
This feature is very important

**Comment by dfilatov** [comment]
+1

**Comment by curvedmark** [comment]
This can be done by modifying the evaluator, but it actually sounds like a need for a built-in global variable like `$__dirname`, which conceptually resolves to the dir path of the roole file, but resolves to the relative path from the dir path of the css file to that of the roole file after compilation.

**tmp/base.rl:**

``` css
@import 'block/include.rl';
```

**tmp/block/include.rl:**

``` css
.block {
    background: url("$__dirname/1.png");
}
```

```
roole tmp/base.rl
```

So roole knows the compiled css file is located in `tmp/`, and the dirname of `include.rl` is `tmp/block/`, the relative path is `block/`, which `$__dirname` should be evaluated to.

This has the benefit of not forcing all `url()` functions to be relative to the roole file, and will work for urls that are not wrapped in `url()` (e.g, `@import 'file.css' screen`).

**Comment by mdevils** [comment]
I would appreciate introduction of `$__dirname` variable.

**Comment by curvedmark** [comment]
but it's unclear what the result should be if the user decides to compile to stdout, which doesn't have a path by itself.

**Comment by mdevils** [comment]
I think for this case there should be a CLI/API argument of output directory path.

**Comment by mdevils** [comment]
Or just use `cwdir`. But I would better use an additional option as in my case I need the output without writing to files.

**Comment by curvedmark** [comment]
An option sounds reasonable. It will override the path of the css file if provided, and fallback to `cwdir` if compile to stdout and this option is not provided.

The value of the option should be the would-be path of the generated css file.

Sounds good?

**Comment by mdevils** [comment]
Yes, it would be great!

**Comment by curvedmark** [comment]
Landed in master.

`--out` is the flag, which is the would-be dir of the generated css file.

Let me know if it works. Please open a new issue regarding `$__dirname` if it doesn't.

**Comment by curvedmark** [comment]
I'm thinking about making all relative urls to be relative to the current file. No need to add `$__dirname`. If you want predicable urls, just make them absolute.

Will this change bring trouble to you?

**Comment by mdevils** [comment]
This change would be awesome for me.

**Comment by mishanga** [comment]
:+1:

**Comment by mishanga** [comment]
`$__dirname` looks like ugly hack :-/

**Comment by curvedmark** [comment]
I'm thinking of making relative urls be relative to cwd, instead of the dir of the current file.

The problem with the latter behavior is that when the roole file is nested very deeply, it becomes very awkward to refer to the image files at the top-level.

img/tab-bg.png

```
image content
```

components/tabs/small/index.roo

``` css
.tab {
  background: url(../../../tab-bg.png);
}
```

If, however, relative urls are relative to cwd, then you can simply write:

components/tabs/small/index.roo

``` css
.tab {
  background: url(img/tab-bg.png);
}
```

Another benefit is for writing libraries. Imagine you wrote a button module, and you want users to be able to specify a background image. 

node_modules/button/index.roo

``` css
.btn {
  background: url($img-url);
}
```

If the url were relative the dir of the file, user would have to write:

img/btn-bg.png

```
image content
```

roo/my-button.roo

``` css
$img-url = '../../img/btn-bg.png'; // the relative path from node_modules/button/ to the image
@import 'button';
```

Which is a nightmare, comparing to 

roo/my-button.roo

``` css
$img-url = 'img/btn-bg.png';
@import 'button';
```

Nested libraries could make the situation worse. 

Being relative to cwd is also how the `fs` module in node works. So it should be familiar with most js developers.

What you guys think? Or you have a better idea? :)

**Comment by curvedmark** [comment]
I changed the issue title to better reflect the problem we are discussing all along. Hope you don't mind.

**Comment by mishanga** [comment]
We are using [BEM methodology](http://bem.info/). It's very useful for us to have current file related urls.
With BEM you can easily rename/replace blocks and their folders.

@mdevils @kizu @veged @dfilatov guys, help me =)

Project tree:

```
blocks/logo/logo.roo
blocks/logo/logo.png
blocks/button/button.roo
blocks/button/__icon/button__icon.png
pages/index/index.roo <= compiled roo-file
pages/index/index.css <= compiled css-file
pages/index/_index.css <= minificated css-file
```

Source content:

``` css
/* logo.roo */
.logo { background: url(logo.png) }
```

``` css
/* button.roo */
.button__icon { background: url(__icon/button__icon.png) }
```

Compiled files:

``` css
/* index.roo */
@import './blocks/logo/logo.roo';
@import './blocks/button/button.roo';
```

``` css
/* index.css */
.logo { background: url(/blocks/logo/logo.png) }
.button__icon { background: url(/blocks/button/__icon/button__icon.png) }
```

**Comment by veged** [comment]
At least it can be parametrized. Cause I'm sure a lot of peoples treat relative urls as really relative to file (not relative to CWD). For example if you use Vim and do `gf` on file path or if you use IntelliJ IDEA and Cmd+click on file path they both lookup it relative to file. CWD is very unstable and unpredictable -- if you treat relative paths as relative to CWD you indirectly assume that user run program only in project root.

**Comment by dfilatov** [comment]
+1 to @veged

**Comment by curvedmark** [comment]
@mishanga This example really helps. So there are basically three types of directory structures:

## Modularized styles and images
- roole files and images exist in the same directory
  - `styles/btn/bg.png`
  - `styles/btn/index.roo`
    
    ``` css
    .btn {
        background: url(bg.png);
    }
    ```
  - `styles/index.roo`
    
    ``` css
    @import './btn';
    ```
- css is compiled to the same directory
  - `styles/index.css`
    
    ``` css
    .btn {
        background: url(btn/bg.png);
    }
    ```

In this case, it helps if urls are relative to the dir of the current file, since the image to be referred to usually live very closed to the current file.

## Isolated styles and images
- roole files and images exist in different directories
  - `img/btn-bg.png`
  - `roo/btn/index.roo`
    
    ``` css
    .btn {
        background: url(img/btn-bg.png);
    }
    ```
  - `roo/index.roo`
    
    ``` css
    @import './btn';
    ```
- css is compiled to a third different directory
  - `css/index.css`
    
    ``` css
    .btn {
        background: url(../img/btn-bg.png);
    }
    ```

In this case, it helps if urls are relative to cwd, since the image to be referred to usually live very far to the current file, and being relative to cwd make the urls consistent.

## Mixture of the two above
- a library uses modularized styles and images
  - `node_modules/btn/bg.png`
  - `node_modules/btn/index.roo`
    
    ``` css
    .btn {
        background: url(bg.png);
    }
    ```
- a user consuming the library uses isolated styles and images
  - `img/tab-bg.png`
  - `roo/tabs/index.roo`
    
    ``````
    ```css
    .tab {
        background: url(img/tab-bg.png);
    }
    ```
    ``````
  - `roo/index.roo`
    
    ``````
    ```css
    @import 'btn';
    @import './tabs';
    ```
    ``````
- css is compiled to a third different directory
  - `css/index.css`
    
    ``` css
    .btn {
        background: url(../node_modules/btn/bg.png);
    }
    
    .tab {
        background: url(../img/tab-bg.png);
    }
    ```

In this case, neither being relative to the dir of the current file or cwd helps. the library and the users want different behavior simultaneously. So make an option for this behavior as suggested by @veged won't work here.

I think the only logical solution here is to bring back `$__dirname`: urls are relative to the cwd, to make them relative to the dir of the current file, append `$__dirname` to the url.

So the third type now becomes:
- a library uses modularized styles and images
  - `node_modules/btn/bg.png`
  - `node_modules/btn/index.roo`
    
    ``` css
    .btn {
        background: url("$_dirname/bg.png");
    }
    ```
- a user consuming the library uses isolated styles and images
  - `img/tab-bg.png`
  - `roo/tabs/index.roo`
    
    ``````
    ```css
    .tab {
        background: url(img/tab-bg.png);
    }
    ```
    ``````
  - `roo/index.roo`
    
    ``````
    ```css
    @import 'btn';
    @import './tabs';
    ```
    ``````
- css is compiled to a third different directory
  - `css/index.css`
    
    ``` css
    .btn {
        background: url(../node_modules/btn/bg.png);
    }
    
    .tab {
        background: url(../img/tab-bg.png);
    }
    ```
